spring.application.name=AIChatBot
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
server.port=9999

// url or api endpoint for postman http://localhost:9999/chat?prompt=Explain Spring Boot